Check the status of all branches, not just the one checked out

diff --git a/tools/fetch-with-status b/tools/fetch-with-status
--- a/tools/fetch-with-status
+++ b/tools/fetch-with-status
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+get_all_branch_info()
+{
+    git branch|sed -e 's/(no branch)/NOBRANCH/' -e 's/^\* //' -e 's/^  *//'
+}
+
 get_branch_info()
 {
     git branch|grep '^\* '|sed 's/(no branch)/NOBRANCH/'
@@ -61,62 +66,65 @@ fi
 )
 
 branch=`guess_branch`
-upstream=origin/"$branch"
-if [ "$branch" ]
-then
-        git cat-file -e "$upstream" || upstream=origin/master
-        diffs=`git diff "$upstream"|head -1`
-else
-        echo "No branch checked out."
-fi
-
-in_repo_local=
-in_repo=
-if [ "$diffs" ]
-then
-	in_repo_local=`does_contain "$upstream" "$branch"`
-	[ "$in_repo_local" ] && echo "A local commit is not in the remote repo: `print_branch $branch`."
-
-	in_repo=`does_contain "$branch" "$upstream"`
-	[ "$in_repo" ] && echo "Local branch does not have a commit from the remote repo: `print_branch $upstream`."
-fi
-
-git branch -a -v|sed -e '/^  origin/d' -e 's/..//'|awk '{print $2}'|sort -u>/tmp/$$-branchlist
-git branch -a -v|awk '/^  origin/ {print $2}'|sort -u>/tmp/$$-originlist
-local_only=`comm -23 /tmp/$$-{branchlist,originlist}`
-
-# [ ! "$local_only" ] || [ "$in_repo_local" ] || [ "$in_repo" ] ||
-	# echo "The remote repo is missing a commit from a non-checked-out local branch (or no branch is checked out at all)."
-
-for i in $local_only
+for branch in `get_all_branch_info`
 do
-      # TODO: this match is overly general
-      case `print_branch $i` in
-      *"$branch"* )
-		continue
-		;;
-      esac
-
-      for j in `cat /tmp/$$-originlist`
-      do
-         branch_in_repo+=`does_contain "$i" "$j"`
-      done
-      [ "$branch_in_repo" ] || (echo -n "Commit not in remote repo: `print_branch $i`" && echo)
-
-      for j in `cat /tmp/$$-originlist`
-      do
-         repo_in_branch+=`does_contain "$j" "$i"`
-      done
-      if [ ! "$repo_in_branch" ]
-      then
-	echo -n "Local branch is missing a commit: `print_branch $i`"
-	echo
-      else
-        [ "$branch_in_repo" ] &&
-	echo "The HEAD of a local branch is not current with any remote branch: `print_branch $i`"
-      fi
-      repo_in_branch=
-      branch_in_repo=
+	upstream=origin/"$branch"
+	if [ "$branch" ]
+	then
+	        git cat-file -e "$upstream" || upstream=origin/master
+	        diffs=`git diff "$upstream"|head -1`
+	else
+	        echo "No branch checked out."
+	fi
+	
+	in_repo_local=
+	in_repo=
+	if [ "$diffs" ]
+	then
+		in_repo_local=`does_contain "$upstream" "$branch"`
+		[ "$in_repo_local" ] && echo "A local commit is not in the remote repo: `print_branch $branch`."
+	
+		in_repo=`does_contain "$branch" "$upstream"`
+		[ "$in_repo" ] && echo "Local branch does not have a commit from the remote repo: `print_branch $upstream`."
+	fi
+	
+	git branch -a -v|sed -e '/^  origin/d' -e 's/..//'|awk '{print $2}'|sort -u>/tmp/$$-branchlist
+	git branch -a -v|awk '/^  origin/ {print $2}'|sort -u>/tmp/$$-originlist
+	local_only=`comm -23 /tmp/$$-{branchlist,originlist}`
+	
+	# [ ! "$local_only" ] || [ "$in_repo_local" ] || [ "$in_repo" ] ||
+		# echo "The remote repo is missing a commit from a non-checked-out local branch (or no branch is checked out at all)."
+	
+	for i in $local_only
+	do
+	      # TODO: this match is overly general
+	      case `print_branch $i` in
+	      *"$branch"* )
+			continue
+			;;
+	      esac
+	
+	      for j in `cat /tmp/$$-originlist`
+	      do
+	         branch_in_repo+=`does_contain "$i" "$j"`
+	      done
+	      [ "$branch_in_repo" ] || (echo -n "Commit not in remote repo: `print_branch $i`" && echo)
+	
+	      for j in `cat /tmp/$$-originlist`
+	      do
+	         repo_in_branch+=`does_contain "$j" "$i"`
+	      done
+	      if [ ! "$repo_in_branch" ]
+	      then
+		echo -n "Local branch is missing a commit: `print_branch $i`"
+		echo
+	      else
+	        [ "$branch_in_repo" ] &&
+		echo "The HEAD of a local branch is not current with any remote branch: `print_branch $i`"
+	      fi
+	      repo_in_branch=
+	      branch_in_repo=
+	done
 done
 
 rm -rf /tmp/$$-{branchlist,originlist}
